default: true

# Max line length
MD013:
  line_length: 120
  code_block_line_length: 120

# Duplicate Headings for different sections
MD024:
  allow_different_nesting: true
  siblings_only: true

# Multiple top level headings
MD025: false

# Allow inline HTML
MD033: false
