version: "3.9"
services:
  db:
    build: ./db
    volumes:
      - ./data/dev:/var/lib/postgresql/data
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 15432:5432
    env_file:
      - .env.dev
  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    working_dir: /src
    entrypoint: bash ./entrypoint.sh --dev
    volumes:
      - ./api:/src
      - .cache/api:/src/target
    ports:
      - 15000:5000
    env_file:
      - .env
      - .env.dev
  web:
    user: 1000:1000
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    working_dir: /app
    entrypoint: bash ./entrypoint.sh --dev
    volumes:
      - ./web:/app
    ports:
      - 16655:6655
      - 24678-24690:24678-24690
      - 4000:4000
    env_file:
      - .env.dev
  bot:
    build:
      context: ./bot
      dockerfile: dev.Dockerfile
    working_dir: /workspace/bot
    entrypoint: bash ./entrypoint.sh --dev
    volumes:
      - ./bot:/workspace/bot
    env_file:
      - .env.dev
  redis:
    image: redis
    ports:
      - 16379:6379
    volumes:
      - ./data/dev/redis:/data
    env_file:
      - .env.dev
